# Generated by Django 4.0.4 on 2022-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_vtype_property_bathrooms_vehichle_vehichle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehichle',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
