# Generated by Django 4.0.4 on 2022-05-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_vehichle_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehichle',
            name='premium',
        ),
        migrations.AddField(
            model_name='property',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
