# Generated by Django 4.0.4 on 2022-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_vehichle_premium_property_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
